version: '3'
services:
  postgres:
    image: postgres:10.4
    container_name: pg_dev
    volumes:
      - ~/data/pgsql/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  natstreaming:
    image: nats-streaming
    container_name: natstream
    volumes:
      - ~/nat_store:/nat_store
      - $GOPATH/src/auservices/config/message-streaming:/message_streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -c message_streaming/au-streaming.cfg
  