// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CategoryType int32

const (
	CategoryType_EXPENSE CategoryType = 0
	CategoryType_INCOME  CategoryType = 1
)

var CategoryType_name = map[int32]string{
	0: "EXPENSE",
	1: "INCOME",
}
var CategoryType_value = map[string]int32{
	"EXPENSE": 0,
	"INCOME":  1,
}

func (x CategoryType) String() string {
	return proto.EnumName(CategoryType_name, int32(x))
}
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{0}
}

type PingMessage struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{0}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type User struct {
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type Category struct {
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 CategoryType `protobuf:"varint,4,opt,name=type,proto3,enum=api.CategoryType" json:"type,omitempty"`
	User                 *User        `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{2}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetType() CategoryType {
	if m != nil {
		return m.Type
	}
	return CategoryType_EXPENSE
}

func (m *Category) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CategoryQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	User                 *User    `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryQuery) Reset()         { *m = CategoryQuery{} }
func (m *CategoryQuery) String() string { return proto.CompactTextString(m) }
func (*CategoryQuery) ProtoMessage()    {}
func (*CategoryQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{4}
}
func (m *CategoryQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryQuery.Unmarshal(m, b)
}
func (m *CategoryQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryQuery.Marshal(b, m, deterministic)
}
func (dst *CategoryQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryQuery.Merge(dst, src)
}
func (m *CategoryQuery) XXX_Size() int {
	return xxx_messageInfo_CategoryQuery.Size(m)
}
func (m *CategoryQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryQuery proto.InternalMessageInfo

func (m *CategoryQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *CategoryQuery) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CategoryList struct {
	Categories           []*Category `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryList) Reset()         { *m = CategoryList{} }
func (m *CategoryList) String() string { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()    {}
func (*CategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{5}
}
func (m *CategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryList.Unmarshal(m, b)
}
func (m *CategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryList.Marshal(b, m, deterministic)
}
func (dst *CategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryList.Merge(dst, src)
}
func (m *CategoryList) XXX_Size() int {
	return xxx_messageInfo_CategoryList.Size(m)
}
func (m *CategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryList proto.InternalMessageInfo

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CategoryResponse struct {
	ResponseMsg          string   `protobuf:"bytes,2,opt,name=responseMsg,proto3" json:"responseMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryResponse) Reset()         { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()    {}
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{6}
}
func (m *CategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResponse.Unmarshal(m, b)
}
func (m *CategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResponse.Marshal(b, m, deterministic)
}
func (dst *CategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResponse.Merge(dst, src)
}
func (m *CategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryResponse.Size(m)
}
func (m *CategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResponse proto.InternalMessageInfo

func (m *CategoryResponse) GetResponseMsg() string {
	if m != nil {
		return m.ResponseMsg
	}
	return ""
}

type CategortyTypeValues struct {
	Types                map[string]int32 `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CategortyTypeValues) Reset()         { *m = CategortyTypeValues{} }
func (m *CategortyTypeValues) String() string { return proto.CompactTextString(m) }
func (*CategortyTypeValues) ProtoMessage()    {}
func (*CategortyTypeValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_46325fd2ed5528dd, []int{7}
}
func (m *CategortyTypeValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategortyTypeValues.Unmarshal(m, b)
}
func (m *CategortyTypeValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategortyTypeValues.Marshal(b, m, deterministic)
}
func (dst *CategortyTypeValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategortyTypeValues.Merge(dst, src)
}
func (m *CategortyTypeValues) XXX_Size() int {
	return xxx_messageInfo_CategortyTypeValues.Size(m)
}
func (m *CategortyTypeValues) XXX_DiscardUnknown() {
	xxx_messageInfo_CategortyTypeValues.DiscardUnknown(m)
}

var xxx_messageInfo_CategortyTypeValues proto.InternalMessageInfo

func (m *CategortyTypeValues) GetTypes() map[string]int32 {
	if m != nil {
		return m.Types
	}
	return nil
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*Category)(nil), "api.Category")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*CategoryQuery)(nil), "api.CategoryQuery")
	proto.RegisterType((*CategoryList)(nil), "api.CategoryList")
	proto.RegisterType((*CategoryResponse)(nil), "api.CategoryResponse")
	proto.RegisterType((*CategortyTypeValues)(nil), "api.CategortyTypeValues")
	proto.RegisterMapType((map[string]int32)(nil), "api.CategortyTypeValues.TypesEntry")
	proto.RegisterEnum("api.CategoryType", CategoryType_name, CategoryType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/api.Ping/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ping_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// CategoryServicesClient is the client API for CategoryServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryServicesClient interface {
	FindCatetories(ctx context.Context, in *CategoryQuery, opts ...grpc.CallOption) (*CategoryList, error)
	AddCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*CategoryResponse, error)
	GetAllCategoryTypeValues(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategortyTypeValues, error)
}

type categoryServicesClient struct {
	cc *grpc.ClientConn
}

func NewCategoryServicesClient(cc *grpc.ClientConn) CategoryServicesClient {
	return &categoryServicesClient{cc}
}

func (c *categoryServicesClient) FindCatetories(ctx context.Context, in *CategoryQuery, opts ...grpc.CallOption) (*CategoryList, error) {
	out := new(CategoryList)
	err := c.cc.Invoke(ctx, "/api.CategoryServices/FindCatetories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServicesClient) AddCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*CategoryResponse, error) {
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, "/api.CategoryServices/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServicesClient) GetAllCategoryTypeValues(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategortyTypeValues, error) {
	out := new(CategortyTypeValues)
	err := c.cc.Invoke(ctx, "/api.CategoryServices/GetAllCategoryTypeValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServicesServer is the server API for CategoryServices service.
type CategoryServicesServer interface {
	FindCatetories(context.Context, *CategoryQuery) (*CategoryList, error)
	AddCategory(context.Context, *Category) (*CategoryResponse, error)
	GetAllCategoryTypeValues(context.Context, *Empty) (*CategortyTypeValues, error)
}

func RegisterCategoryServicesServer(s *grpc.Server, srv CategoryServicesServer) {
	s.RegisterService(&_CategoryServices_serviceDesc, srv)
}

func _CategoryServices_FindCatetories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServicesServer).FindCatetories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CategoryServices/FindCatetories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServicesServer).FindCatetories(ctx, req.(*CategoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryServices_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServicesServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CategoryServices/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServicesServer).AddCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryServices_GetAllCategoryTypeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServicesServer).GetAllCategoryTypeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CategoryServices/GetAllCategoryTypeValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServicesServer).GetAllCategoryTypeValues(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CategoryServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CategoryServices",
	HandlerType: (*CategoryServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindCatetories",
			Handler:    _CategoryServices_FindCatetories_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _CategoryServices_AddCategory_Handler,
		},
		{
			MethodName: "GetAllCategoryTypeValues",
			Handler:    _CategoryServices_GetAllCategoryTypeValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_46325fd2ed5528dd) }

var fileDescriptor_api_46325fd2ed5528dd = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x6d, 0xd2, 0x6b, 0x27, 0xde, 0x11, 0xc7, 0x07, 0x42, 0x40, 0x09, 0x2b, 0x62,
	0x15, 0x2c, 0x12, 0x15, 0xaa, 0xe0, 0x8b, 0xf3, 0x8c, 0x0f, 0x60, 0xcf, 0x33, 0x55, 0xf1, 0x6d,
	0x6c, 0x96, 0xb0, 0x98, 0x4b, 0xe2, 0xee, 0xb6, 0x90, 0x2f, 0xe0, 0x0b, 0x3f, 0x99, 0x1f, 0x4b,
	0x76, 0x9b, 0xb6, 0x09, 0x22, 0xbe, 0x9b, 0xf9, 0x67, 0x66, 0x76, 0xe6, 0x37, 0x13, 0x98, 0xa4,
	0x35, 0x9f, 0xd5, 0xa2, 0x52, 0x15, 0x0e, 0xd3, 0x9a, 0xd3, 0xfb, 0xe0, 0x5e, 0xf0, 0x32, 0x5f,
	0x30, 0x29, 0xd3, 0x9c, 0x61, 0x00, 0xe3, 0x5c, 0x30, 0xa6, 0x78, 0x99, 0xfb, 0x24, 0x24, 0xd3,
	0x49, 0xb2, 0xf7, 0xe9, 0x6d, 0xb0, 0x3f, 0x4b, 0x26, 0xf0, 0x26, 0x8c, 0xd6, 0x92, 0x09, 0x9e,
	0xb5, 0x11, 0xad, 0x47, 0x7f, 0x12, 0x18, 0x9f, 0xa5, 0x8a, 0xe5, 0x95, 0x68, 0x10, 0xc1, 0x2e,
	0xd3, 0x4b, 0xe6, 0x0f, 0x4c, 0x88, 0xb1, 0x31, 0x04, 0x37, 0x63, 0x72, 0x25, 0x78, 0xad, 0x78,
	0x55, 0xfa, 0x43, 0xf3, 0xa9, 0x2b, 0xe1, 0x5d, 0xb0, 0x55, 0x53, 0x33, 0xdf, 0x0e, 0xc9, 0xf4,
	0x24, 0xba, 0x3a, 0xd3, 0xcd, 0xee, 0x4a, 0x7e, 0x6a, 0x6a, 0x96, 0x98, 0xcf, 0x78, 0x0b, 0x6c,
	0xfd, 0xa6, 0xef, 0x84, 0x64, 0xea, 0x46, 0x13, 0x13, 0xa6, 0x5b, 0x4b, 0x8c, 0x4c, 0x8f, 0xc0,
	0x89, 0x2f, 0x6b, 0xd5, 0xd0, 0x57, 0x70, 0xbc, 0xcb, 0xfe, 0xb8, 0x66, 0xa2, 0xc1, 0xeb, 0xe0,
	0xfc, 0xd0, 0x46, 0xdb, 0xf9, 0xd6, 0xf9, 0x5f, 0xb9, 0x17, 0x70, 0x65, 0x57, 0xe5, 0x3d, 0x97,
	0x0a, 0x1f, 0x02, 0xac, 0xb6, 0x3e, 0x67, 0xd2, 0x1f, 0x84, 0xc3, 0xa9, 0x1b, 0x1d, 0xf7, 0x5a,
	0x4d, 0x3a, 0x01, 0xf4, 0x09, 0x78, 0x7b, 0x9d, 0xc9, 0xba, 0x2a, 0xa5, 0x21, 0x21, 0x5a, 0x7b,
	0x21, 0xf3, 0x16, 0x52, 0x57, 0xa2, 0xbf, 0x08, 0x5c, 0x6b, 0xd3, 0x94, 0x19, 0xfd, 0x4b, 0x5a,
	0xac, 0x99, 0xc4, 0x67, 0xe0, 0x68, 0x04, 0xd2, 0x27, 0xe6, 0xdd, 0x3b, 0xdd, 0x77, 0xbb, 0x81,
	0x33, 0x6d, 0xca, 0xb8, 0x54, 0xa2, 0x49, 0xb6, 0x19, 0xc1, 0x1c, 0xe0, 0x20, 0xa2, 0x07, 0xc3,
	0xef, 0x6c, 0x07, 0x42, 0x9b, 0x1a, 0xce, 0x46, 0xe7, 0x9a, 0x76, 0x9c, 0x64, 0xeb, 0x3c, 0x1f,
	0xcc, 0xc9, 0x83, 0x7b, 0x07, 0x02, 0xba, 0x02, 0xba, 0x70, 0x14, 0x7f, 0xbd, 0x88, 0xcf, 0x97,
	0xb1, 0x67, 0x21, 0xc0, 0xe8, 0xdd, 0xf9, 0xd9, 0x87, 0x45, 0xec, 0x91, 0x68, 0x0e, 0xb6, 0xbe,
	0x26, 0x7c, 0x04, 0xe3, 0x65, 0xda, 0xbc, 0x65, 0x45, 0x51, 0xa1, 0x67, 0x5a, 0xec, 0x1c, 0x59,
	0xf0, 0x97, 0x42, 0xad, 0xe8, 0x37, 0x39, 0x60, 0x5a, 0x32, 0xb1, 0xe1, 0x2b, 0x33, 0xec, 0xc9,
	0x6b, 0x5e, 0x66, 0x5a, 0x57, 0x06, 0x26, 0x62, 0x8f, 0xb3, 0x59, 0x6a, 0xd0, 0x3f, 0x13, 0xbd,
	0x22, 0x6a, 0xe1, 0x53, 0x70, 0x4f, 0xb3, 0x6c, 0x7f, 0x8e, 0xfd, 0xfd, 0x04, 0x37, 0xfa, 0xeb,
	0x6a, 0xb9, 0x53, 0x0b, 0x5f, 0x82, 0xff, 0x86, 0xa9, 0xd3, 0xa2, 0xe8, 0xce, 0xdb, 0xa2, 0x07,
	0x93, 0x64, 0x2e, 0x2b, 0xf0, 0xff, 0xc5, 0x9d, 0x5a, 0xdf, 0x46, 0xe6, 0xf7, 0x7a, 0xfc, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0xc2, 0x16, 0x86, 0x6b, 0x03, 0x00, 0x00,
}
